### ISSUE TITLE
Fails at first time

### ISSUE THREAD

**Issue by dazhbog** [JelmerT/cc2538-bsl#13]
Hi there,

Ive been using the script to program the cc2538 for a while now and it works great.

I have a little issue when programming the chip. After the chip goes into the bootloader the first attempt seems to always fail. Here are the traces below for the first and second attempt. The second attempt succeded.

First:
```
python ../../../tools/cc2538-bsl/cc2538-bsl.py -e -w -v -V -b 115200 udp-client.bin                           
Opening port /dev/ttyUSB0, baud 115200                                                                        
Reading data from udp-client.bin                             
Connecting to target...                      
*** sending synch sequence            
Unrecognised response 0x0 to Synch (0x55 0x55)                                                                
ERROR: Can't connect to target. Ensure boot loader is started. (no answer on synch sequence)     
```

Second:
```
python ../../../tools/cc2538-bsl/cc2538-bsl.py -e -w -v -V -b 115200 udp-client.bin
Opening port /dev/ttyUSB0, baud 115200
Reading data from udp-client.bin
Connecting to target...
*** sending synch sequence
*** GetChipId command (0x28)
*** received 6 bytes
*** GetStatus command (0x23)
*** received 3 bytes
Command Successful
    Target id 0xb964, CC2538
Erasing 524288 bytes starting at address 0x200000
*** Erase command(0x26)
*** GetStatus command (0x23)
*** received 3 bytes
[... etc]
```

I tried putting delays between the reset and the programming and also tried to flush the serial port before the programming starts. 

Im using Ubuntu 14.04 64bit.

Let me know if you have any ideas.

Thanks.

**Comment by JelmerT** [comment]
@dazhbog did you get this fixed eventually?

**Comment by davidrojas** [comment]
I have exactly the same problem, @dazhbog . Did you find a solution?
I noticed that if I tune down the speed to 38400 or less, then it always works.

**Comment by JelmerT** [comment]
@davidrojas did you try increasing the `timeout` value?

**Comment by davidrojas** [comment]
Yes, I already tried that, makes no difference.

**Comment by JelmerT** [comment]
@davidrojas what hardware are you using?

**Comment by davidrojas** [comment]
A custom board with an ftdi chip FT232RQ

**Comment by dazhbog** [comment]
Sorry for the late reply, I made another, custom board with very short traces and a different FTDI chip and now i can take the baud rate up to 500000. I still have to manually bring the board into the bootloader mode though..

**Comment by JelmerT** [comment]
Using the auto bootloader start feature only works if your hardware supports it (RTS and DTR should be connected to the chip). 
There might be some other issues with it too, for more info have a look at #27

**Comment by davidrojas** [comment]
I've done some tests, and this behaviour is somewhat erratic. I noticed it is dependant on the actual binary that you uploaded before, but I don't know exactly what it is. If some peripheral is activated/deactivated, low power mode, etc. in the previous firmware, it always takes two attempts to flash (bootloader always comes up alright everytime, you can check because the LEDs are half-way on). Then if I try a different code, it flashes first time always. We could start with a hello world and then add timers, putting it in LPM1/2, etc. until we see when it starts failing at first time.

**Comment by g-oikonomou** [comment]
I've been in a situation where synch fails after a reset and I have to reset again. I've not double checked whether the cause is the same as what is being discussed here, but will do.

>  Perform the following steps to successfully receive a packet:
1. Waiting for the device to return non-zero data is important because the device can send zero bytes between a sent and received data packet. The first nonzero byte received is the size of the packet being received.

Could it be that we simply need to wait for the first non-zero while waiting for an ACK/NACK rather than hard-coding a two-byte read?

**Comment by g-oikonomou** [comment]
I think we need to re-open this.

I now have a theory: When the running firmware sends stuff out of the UART, these things get somehow buffered (on some FTDI on the board? somewhere in the driver or line discipline?). The first N bytes read after sending the synch sequence are exactly those bytes. The reason we see them as zeros is because we open the port at a different baud rate than the one those chars were sent at. In fact, if we force `-b {115200 , 230400 , 460800}` we may get non-zeros. It looks like we must first send something to the device before those bytes start streaming down our line, which is why (I assume) `flushInput()` doesn't seem enough to prevent this.

Since we cannot rely on them to be all zeros, I can only think of changing `_wait_for_ack` to reading from the line byte-byte byte and check the last two bytes for the ACK/NACK sequence. This needs a non-zero timeout. Something like:

```
    def _wait_for_ack(self, info = "", timeout = 1):
        stop = time.time() + timeout
        got = bytearray(2)
        while got[-2] != 00 or got[-1] not in (0xCC, 0x33):
            got += self._read(1)
            if time.time() > stop:
                break

        mdebug(10, "0x%02x: 0x%s" % (len(got), " ".join("%02X" % x for x in got)))

        # wait for ask
        ask = got[-1]

        if ask == 0xCC:
            # ACK
            return 1
        elif ask == 0x33:
            # NACK
            mdebug(10, "Target replied with a NACK during %s" % info)
            return 0

        # Unknown response
        mdebug(10, "Unrecognised response 0x%x to %s" % (ask, info))
        return 0
```

**Comment by JelmerT** [comment]
I'm also noticing some failed first-attempts. I always assumed it was because I didn't properly (manually) start the boot loader, but now that I'm looking closer at the problem, I'm indeed also sometimes getting a bunch of zeroes, but also sometimes non-zero junk values.

I indeed thought `flushInput()` fixed all this in 34d43457443492ab3904a8ef50169d9250263329, but apparently the chip / driver has a second buffer that dumps in the last buffer when emptied.

The problem sounds a lot like this one: https://groups.google.com/forum/#!topic/linux.kernel/kCExd47w9HI (From '07). So it might have something to do with a double buffer in the cdc-acm driver. (I'm seeing the problem on OSX)

So a quick fix might be to call `flushInput()` multiple times. Your solution seems a bit cleaner though, and it takes into account the possible zero bytes before a useful packet.

I'll try both and report back.

**Comment by g-oikonomou** [comment]
I had a bit of a eureka moment to try and close the port manually before script exit. Shouldn't make any difference in theory but I'll give it a stab later!

**Comment by g-oikonomou** [comment]
Testing on OS X here as well. `cmd.close()` doesn't make any difference. Behaviour consistent with Zolertia RE-Mote (some FTDI, FT2232 I think) and SmartRF + CC2650EM
